Http:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 端口号
  port: 8070 # 服务端口号
  ## pprof
  pprof:
    ## pprof http 监听端口
    port: 8071

Logger:
  # 日志存放路径
  path: logs

Jwt:
  # token 密钥，生产环境时及的修改
  secret: xwc
  # token 过期时间 单位：秒
  expire: 7200

Database:
  # 数据库类型 mysql, sqlite3, postgres, sqlserver
  # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
  driver: postgres
  # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  #source: user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  host: 192.168.1.212
  database: "admin"
  user: root
  password: root
  port: 5432

Redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0
