// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/sys/api/:id": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新api接口",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "更新api接口",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SysApi"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/api/generate": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "生成接口",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "生成接口",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/api/list": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "接口列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "api"
                ],
                "summary": "接口列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.SysApi"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/sys/menu": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "新增菜单",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "新增菜单",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddMenuParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/menu/:id": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新菜单",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "更新菜单",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateMenuParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除菜单",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "删除菜单",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/menu/list": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "菜单列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "menu"
                ],
                "summary": "菜单列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页面",
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RoleListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/sys/role": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "增加角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "增加角色",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddRoleParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/role/:id": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateRoleParam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "删除角色",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/role/list": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "角色列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "角色列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页面",
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.RoleListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/sys/token/login": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户登录接口",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/token/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户退出",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "用户退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/token/refresh": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户token刷新",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "用户token刷新",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserToken"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/user": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "新增用户",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/user/:user_id": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新用户",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "删除用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/user/:user_id/role": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "更新用户角色",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "更新用户角色",
                "parameters": [
                    {
                        "description": "body",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateUserRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/v1/sys/user/list": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "用户列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "用户列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页面",
                        "name": "page_no",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddMenuParam": {
            "type": "object",
            "required": [
                "menu_name",
                "menu_type",
                "status"
            ],
            "properties": {
                "apis": {
                    "description": "api接口id集合",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "icon": {
                    "description": "菜单图标",
                    "type": "string"
                },
                "is_show": {
                    "description": "是否显示1:正常 0:停用",
                    "type": "integer"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "menu_type": {
                    "description": "菜单类型 1:目录 2:菜单 3:按钮",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                },
                "parent_id": {
                    "description": "父级菜单",
                    "type": "integer"
                },
                "path": {
                    "description": "菜单路径",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "minimum": 0
                },
                "status": {
                    "description": "状态 -1:删除 1:正常 2:停用",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "title": {
                    "description": "菜单标题",
                    "type": "string"
                }
            }
        },
        "dto.AddRoleParam": {
            "type": "object",
            "required": [
                "menu_ids",
                "role_key",
                "role_name"
            ],
            "properties": {
                "flag": {
                    "description": "标志位",
                    "type": "string"
                },
                "menu_ids": {
                    "description": "菜单id集合",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "role_key": {
                    "description": "角色唯一key",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "role_sort": {
                    "description": "角色排序",
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "dto.AddUserReq": {
            "type": "object",
            "required": [
                "password",
                "role_id",
                "username"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nick_name": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "role_id": {
                    "description": "角色id集合",
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 0,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    }
                },
                "sex": {
                    "description": "性别",
                    "type": "string"
                },
                "username": {
                    "description": "用户名(唯一且不能修改)",
                    "type": "string"
                }
            }
        },
        "dto.RoleInfo": {
            "type": "object",
            "properties": {
                "role_id": {
                    "description": "角色id",
                    "type": "integer"
                },
                "role_name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "dto.RoleListResp": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "数据总数",
                    "type": "integer"
                },
                "data": {
                    "description": "数据集合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SysRole"
                    }
                }
            }
        },
        "dto.SysUserList": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "createBy": {
                    "description": "创建者",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nick_name": {
                    "description": "昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "roles": {
                    "description": "角色集合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RoleInfo"
                    }
                },
                "sex": {
                    "description": "性别",
                    "type": "string"
                },
                "status": {
                    "description": "状态 -1:删除 1:正常 2:停用",
                    "type": "integer"
                },
                "updateBy": {
                    "description": "更新者",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "最后更新时间",
                    "type": "string"
                },
                "user_id": {
                    "description": "用户id",
                    "type": "integer"
                },
                "username": {
                    "description": "用户名(唯一且不能修改)",
                    "type": "string"
                }
            }
        },
        "dto.UpdateMenuParam": {
            "type": "object",
            "required": [
                "menu_name",
                "menu_type",
                "status"
            ],
            "properties": {
                "apis": {
                    "description": "api接口id集合",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "icon": {
                    "description": "菜单图标",
                    "type": "string"
                },
                "is_show": {
                    "description": "是否显示1:正常 0:停用",
                    "type": "integer"
                },
                "menuId": {
                    "description": "id",
                    "type": "integer"
                },
                "menu_name": {
                    "description": "菜单名称",
                    "type": "string"
                },
                "menu_type": {
                    "description": "菜单类型 1:目录 2:菜单 3:按钮",
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                },
                "parent_id": {
                    "description": "父级菜单",
                    "type": "integer",
                    "minimum": 0
                },
                "path": {
                    "description": "菜单路径",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer",
                    "minimum": 0
                },
                "status": {
                    "description": "状态 -1:删除 1:正常 2:停用",
                    "type": "integer",
                    "enum": [
                        1,
                        2
                    ]
                },
                "title": {
                    "description": "菜单标题",
                    "type": "string"
                }
            }
        },
        "dto.UpdateRoleParam": {
            "type": "object",
            "required": [
                "menu_ids",
                "role_name"
            ],
            "properties": {
                "flag": {
                    "description": "标志位",
                    "type": "string"
                },
                "menu_ids": {
                    "description": "菜单id集合",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "role_id": {
                    "description": "角色编码",
                    "type": "integer"
                },
                "role_name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "role_sort": {
                    "description": "RoleKey  *string ` + "`" + `form:\"role_key\" json:\"role_key\"  validate:\"required\" ` + "`" + `  //角色key不能修改",
                    "type": "integer"
                }
            }
        },
        "dto.UpdateUserReq": {
            "type": "object",
            "required": [
                "role_id"
            ],
            "properties": {
                "avatar": {
                    "description": "头像",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "nick_name": {
                    "description": "昵称",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "phone": {
                    "description": "手机号",
                    "type": "string"
                },
                "remark": {
                    "description": "备注",
                    "type": "string"
                },
                "role_id": {
                    "description": "角色id集合",
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 0,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    }
                },
                "sex": {
                    "description": "性别",
                    "type": "string"
                }
            }
        },
        "dto.UpdateUserRoleReq": {
            "type": "object",
            "properties": {
                "role_id": {
                    "description": "角色id集合",
                    "type": "array",
                    "maxItems": 200,
                    "minItems": 0,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "dto.UserListResp": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "数据总数",
                    "type": "integer"
                },
                "data": {
                    "description": "数据集合",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SysUserList"
                    }
                }
            }
        },
        "dto.UserLoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "用户密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名称",
                    "type": "string"
                }
            }
        },
        "dto.UserToken": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "登录token",
                    "type": "string"
                }
            }
        },
        "models.SysApi": {
            "type": "object",
            "properties": {
                "createBy": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "handle": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updateBy": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.SysRole": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "是否是管理员角色",
                    "type": "boolean"
                },
                "createBy": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "flag": {
                    "description": "标志位",
                    "type": "string"
                },
                "remark": {
                    "type": "string"
                },
                "roleId": {
                    "description": "角色编码",
                    "type": "integer"
                },
                "roleKey": {
                    "description": "角色唯一key 不能修改",
                    "type": "string"
                },
                "roleName": {
                    "description": "角色名称",
                    "type": "string"
                },
                "roleSort": {
                    "description": "角色排序",
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "updateBy": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Detail string ` + "`" + `json:\"detail\"` + "`" + `"
                },
                "msg": {
                    "type": "string"
                },
                "ret": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "backend-admin",
	Description:      "后台管理系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
